### ISSUE TITLE
Template Alignment

### ISSUE THREAD

**Issue by knightss27** [knightss27/capr#1]
Currently I am attempting to replace

https://github.com/knightss27/capr/blob/ad2bfd87dcd89fc8d2e48bedeef8fd43b7b5fb12/burmish-pipeline.py#L36

with

https://github.com/knightss27/capr/blob/ad2bfd87dcd89fc8d2e48bedeef8fd43b7b5fb12/burmish-pipeline.py#L42-L47

though I am unsure what template should be used.

Running this currently throws:

```
Traceback (most recent call last):
  File "/root/calc-pipeline/seth/burmish-pipeline.py", line 42, in <module>
    template_alignment(alms,
  File "/usr/local/lib/python3.9/dist-packages/lingrex/align.py", line 190, in template_alignment
    [
  File "/usr/local/lib/python3.9/dist-packages/lingrex/align.py", line 191, in <listcomp>
    align_to_template(alm, struc, template, gap=gap)
  File "/usr/local/lib/python3.9/dist-packages/lingrex/align.py", line 42, in align_to_template
    raise ValueError(
ValueError: sequence ['ɲ̊', 'ɑ̃', 'u', '∼'] and structure ['i', 'n', 'N', 'c', 't'] have different length
```
Which is expected given we likely have a bad template.

@LinguList

**Comment by LinguList** [comment]
It is not the template, it is the structure that was computed there, which is problematic!

**Comment by LinguList** [comment]
You have uncommented one line, which produces the specific "structure":

https://github.com/knightss27/capr/blob/ad2bfd87dcd89fc8d2e48bedeef8fd43b7b5fb12/burmish-pipeline.py#L15-L21

Essential is the `add_entries` with "structure" there. This is where the code adds the specific structure that is used in the template. right now, the structure created there has problems. 

This function is from the `burmtools.py` script, this very long function:

https://github.com/knightss27/capr/blob/ad2bfd87dcd89fc8d2e48bedeef8fd43b7b5fb12/burmtools.py#L99

This hints that there is more data that was used for the parsing, which is missing in this repo (specifically the orthography profiles).

**Comment by LinguList** [comment]
The software package uses the `segments` package, which has also been advanced by now, but we can dissect this function, I think.

**Comment by LinguList** [comment]
Yet first, we need the additional files.

**Comment by knightss27** [comment]
Just added them in https://github.com/knightss27/capr/commit/bca0bd64408b3930898300ddd7b7981a6a2f70a9 ! That should have all the ortho profiles and files used to create the structures. Also I agree now that you pointed it out that the error is related to the structure, I had actually thought this up before but then foolishly didn't think the capital letters like N/M were in the existing file as I couldn't see any at the top!

**Comment by LinguList** [comment]
I tried to run now, but need to install foma first. With all dependencies, etc. it is a bit tedious.

**Comment by LinguList** [comment]
Okay, now parts are running, and I am in a position where I can check and veryify. But I'll have to do something else now and will try to be back later.

**Comment by knightss27** [comment]
No worries, thanks again for any help/advice you can give, even if just pointing me in a direction. I don't exactly have any prolific linguistic experience, so I very much appreciate any help deciphering where the code isn't working vs. where there is an error in the linguistic process.

**Comment by knightss27** [comment]
Also seems as though it is not a problem with the data but a problem with the `burmish_parse` function you mentioned above (for that specific case).

The output in `output/burmish-pipeline/stage1/burmish-stage1.tsv` shows:
`360	Rangoon	sprout / shoot	358	ɑ⁵³hȵɑ̃u⁵³	/ʔ ɑ ⁵³ + ɲ̊ ɑ̃ u ∼	i n t + i n N c t`

Which can be seen on this line here:
https://github.com/knightss27/capr/blob/2d6ef4143c1497f4af777a7ad66336da889d6396/output/burmish-pipeline/stage1/burmish-stage1.tsv#L11112

Unsure what could be causing this, but it is certainly a problem with the `burmish_parse`.

**Comment by knightss27** [comment]
In talking with Prof. Hill, likely a problem to do with our -ortho/-ortho-template transducers for Rangoon, which are being used here:

https://github.com/knightss27/capr/blob/2d6ef4143c1497f4af777a7ad66336da889d6396/burmtools.py#L104-L106

**Comment by LinguList** [comment]
So does burmish_parse produce the faulty STRUCTURE column?

**Comment by LinguList** [comment]
Ah, I see: the parsing procedure is done with the transducer files, which is something we cannot really look into, since they are in some binary format. Originally, we wanted to use orthography profiles to create the STRUCTURE output. We can still arrange this, if you want, it is just a change in the line, let me know, and I show how to do it.

**Comment by knightss27** [comment]
@LinguList This is somewhat unrelated to the question of this issue, but I was wondering if you had any experience getting foma to work on Windows (or even MacOS) with the Python bindings? I have tried building myself with no luck, and it is quite annoying as it is the only piece currently restricting this program to running on Linux machines, but I understand you were able to get it to work when fixing this issue, and so I wondered what OS you had used. No worries if you are using Linux anyways (and please excuse the @).

**Comment by LinguList** [comment]
I used linux, and it took me a while to get it work, as it was not in 
any standard lib, if I remember properly.
